#####
# Tasks to deploy_required_packages
#####

- name: Include variables for CentOS
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'CentOS'

#- name: Include variables for Ubuntu
#  include_vars: "{{ ansible_distribution }}.yml"
#  when: ansible_distribution == 'Ubuntu' or 
#  
#- name: Include variables for Debian
#  include_vars: "{{ ansible_distribution }}.yml"
#  when: ansible_distribution == 'Debian'

- name: Set up Shinken CLI
    command: shinken --init
    args:
      creates: /root/.shinken.ini


