---
- name: Provision landing server
  hosts: local
  connection: local
  gather_facts: False

  vars:
      vars_env: vars/default.yml

  tasks:
    - name: Load environment variables
      include_vars: "{{ vars_env }}"

    - name: Load vault
      include_vars: vars/vault.yml
      no_log: true

    - name: Activate AWS authentication
      include_tasks: tasks/aws-setup-auth.yml

    # - name: Assume AWS role
    #   include_tasks: tasks/aws_assume_role.yml

    - name: Provision EC2 Instance
      include_tasks: tasks/aws-create-instance.yml

    - name: Configuring source folders on landing server
      include_tasks: tasks/landing-setup.yml
