### ansible-playbook playbooks/deploy-seedbox/main.yml -i hosts --vault-password-file vault
### ansible-playbook playbooks/deploy-seedbox/main.yml -i hosts --extra-vars "target=ansible-test"
---
  - name: Deploy a full seedbox
    hosts: seedbox
#    hosts: '{{ target }}'

    vars:
      locale: en_US.UTF-8
      timezone: Europe/Paris
      user_uid: 1010
      user_gid: 1010
      global_install_path: "/home/{{ ansible_ssh_user }}"
      global_config_path: "/home/{{ ansible_ssh_user }}/.config"
      plexdrive_dl_url: https://github.com/dweidenfeld/plexdrive/releases/download/5.0.0/plexdrive-linux-amd64
      plexdrive_mount: /mnt/PlexDrive
      rclone_config_source: ~/Documents/RClone/rclone.conf.txt
      rclone_config_path: "{{ global_config_path }}/rclone/"
      rclone_ACD_mount: /mnt/AmazonCloudDrive
      rclone_GD_mount: /mnt/GoogleDrive
      rclone_DB_mount: /mnt/Dropbox
      deluge_config_path: "{{ global_config_path }}/deluge"
      download_path: "{{ global_install_path }}/downloads"
      sonarr_config_path: "{{ global_config_path }}/sonarr"
      sonarr_db_source: ~/Documents/nzbdrone.db
      sonarr_tv_shows_path: "{{ plexdrive_mount }}/Hulk/TV Shows"
      plex_config_path: "{{ global_config_path }}/plex"
      mkvtoolnix_apt_key_url: https://mkvtoolnix.download/gpg-pub-moritzbunkus.txt
      mkvtoolnix_apt_repo: "deb https://mkvtoolnix.download/ubuntu/xenial/ ./"

    tasks:
     - name: Load vault
       include_vars: vault-seedbox.yml
       no_log: true

     - name: Prepare system
       include_tasks: configure-sytem.yml

     - name : Install Rclone
       include_role:
         name: stefangweichinger.ansible-rclone
       become: yes

     - name: Configure Rclone
       include_tasks: configure-rclone.yml

     - name: Configure Rclone Google Drive
       include_tasks: configure-rclone-drives.yml
       vars:
         rclone_connection_description: Google Drive
         rclone_connection_name: GD
         rclone_mount_point: {{ rclone_GD_mount }}
#
#      - name: Configure Rclone Amazon Cloud Drive
#        include_tasks: configure-rclone-drives.yml
#        vars:
#          rclone_connection_description: Amazon Cloud Drive
#          rclone_connection_name: ACD
#          rclone_mount_point: {{ rclone_ACD_mount }}

     - name: Install PlexDrive
       include_tasks: configure-plexdrive.yml

     - name : Install Docker
       include_role:
         name: angstwad.docker_ubuntu
       vars:
         docker_group_members:
         - "{{ ansible_ssh_user }}"
       become: yes

     - name: Set up docker-compose
       include_tasks: configure-containers.yml

     - name: Spin up "docker composed" apps
       docker_service:
         project_src: "{{ global_install_path }}/seedbox-docker-services"
         state: present

     - name: Configure Deluge
       include_tasks: configure-deluge.yml

     - name: Configure Sonarr
       include_tasks: configure-sonarr.yml

     - name: Configure Muxing
       include_tasks: configure-muxing.yml
