---
version: "2"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
#    ports:
#      - "8112:8112"
#      - "58846:58846"
    environment:
      - PUID={{ user_uid }}
      - PGID={{ user_gid }}
    volumes:
      - {{ deluge_config_path }}:/config
      - {{ deluge_dl_path }}:/downloads    
    restart: always
  sonaar:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - TZ={{ timezone }}
      - PUID={{ user_uid }}
      - PGID={{ user_gid }}
    volumes:
      - {{ sonarr_config_path }}:/config
      - {{ sonarr_tv_shows_path }}:/tv
      - {{ deluge_dl_path }}:/downloads
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    links:
      - deluge
    restart: always
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
#    ports:
#      - "32400:32400"
    environment:
      - TZ={{ timezone }}
      - PLEX_UID={{ user_uid }}
      - PLEX_GID={{ user_gid }}
### Get a PlexClaim here : https://plex.tv/claim
      - PLEX_CLAIM=claim-DxpapDJMoQxpVf5Y4caH
    network_mode: host
    volumes:
      - {{ plex_config_path }}:/config
      - /tmp/plex:/transcode
      - /tmp/plex:/data
      - {{ deluge_dl_path }}:/downloads
      - {{ rclone_GD_mount }}/Hulk:/Hulk:ro



