#####
# Main task file for thruk role
#####

### CentOS only for now
- block:
    - name: '====| ERROR : Distribution not handled by this role yet |===='
      debug:
        msg: '====| Bye ! |===='

    - meta: end_play
  when: ansible_distribution != 'CentOS'

- name: Include common variables
  include_vars: vars-common.yml
  
- debug:
   msg: '====| PLAY : deploy_required_packages |===='
- include: deploy_required_packages.yml
  become: yes

#- debug:
#   msg: '====| PLAY : deploy_shinken |===='
#- include: deploy_shinken.yml
#  become: yes