
- name: Global Linux OS configuration
  vars:
    os_auth_pw_max_age: 99999
    os_auth_timeout: 120
    os_auth_pam_passwdqc_enable: false
    ufw_manage_defaults: false
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding (required for Docker/K8s)
      net.ipv4.ip_forward: 1

  tasks:
    - name: Apply generic system configuration
      include_role:
        name: linux-system_base
    # - name: Apply generic security configuration
    #   include_role:
    #     name: linux-security-base
    - name: Apply OS hardening role
      include_role:
        name: dev-sec.os-hardening
    - name: Setup Wognet access
      include_role:
        name: linux-wognet-access
    - name: Disable ssh root access
      include_role:
        name: linux-disable_root_access
