### ansible-playbook playbooks/linux-setup/main.yml -i ~/Documents/Ansible/hosts --vault-password-file ~/Documents/Ansible/vault.txt --extra-vars "target=[TargetName]" -K -k

- name: Global Linux OS configuration
  hosts: "{{ target }}"
  vars:
    vault_path: ~/Documents/Ansible/vaults/vault-linux-wognet-access.yml
    os_auth_pw_max_age: 99999
    os_auth_timeout: 120
    os_auth_pam_passwdqc_enable: false
    #ufw_manage_defaults: false
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding (required for Docker/K8s)
      net.ipv4.ip_forward: 1

  tasks:
    - name: Load vault
      include_vars: "{{ vault_path }}"
      no_log: true

    - name: Apply generic system configuration
      include_role:
        name: linux-system-base

    - name: Setup Wognet access
      include_role:
        name: linux-wognet-access

    - name: Apply OS hardening role
      include_role:
        name: dev-sec.os-hardening
        apply:
          become: yes

    - name: Disable ssh root access
      include_role:
        name: linux-disable-root-access
