#####
# Tasks to disable_root_access
#####

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    force: yes
    state: present
  notify: Reload SSH

- name: Root access with SSH Key Only
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
    force: yes
    state: present
  notify: Reload SSH
