### ansible-playbook playbooks/gcp-instance_creation_from_image/main.yml --vault-password-file vault

---
- name: Create GCP host
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
      # VARS_ENV: vars/gcp_default.yml
      GCP_REGION: australia-southeast1
      GCP_ZONE: australia-southeast1-b
      GCP_AUTH_KIND: serviceaccount
      GCP_INSTANCE_TYPE: n1-standard-1
      GCP_INSTANCE_DISK_SIZE_GB: 10
      GCP_INSTANCE_CUSTOM_IMAGE: capgemini-quasar-ubuntu-1804
      GCP_INSTANCE_NAME: instance-test

  tasks:
    # - name: Load environment variables
    #   include_vars: "{{ VARS_ENV }}"

    - name: Load vault
      include_vars: vars/vault-quasar.yml
      no_log: true

    - name: Provision Instance
      include_tasks: tasks/gcp-create-instance.yml
