---
    - name: Create directory for docker-compose
      file:
        path: "{{ global_install_path }}/docker-xwiki"
        state: directory

    - name: Copy Docker Compose file
      template:
        src: tpl_docker-compose_xwiki.yml
        dest: "{{ global_install_path }}/docker-xwiki/docker-compose.yml"
