### ansible-playbook playbooks/docker_xwiki-deploy/main.yml -i hosts --vault-password-file vault
### ansible-playbook playbooks/docker_xwiki-deploy/main.yml -i hosts --extra-vars "target=ansible-test"
---
  - name: Deploy xwiki in a Docker container
    hosts: xwiki
#    hosts: '{{ target }}'

    vars:
      locale: en_US.UTF-8
      timezone: Australia/Sydney
      user_uid: 1010
      user_gid: 1010
      global_install_path: "/home/{{ ansible_user_id }}/"

    tasks:
     - name: Load vault
       include_vars: vault-xwiki.yml
       no_log: true

     - name: Prepare system
       include_tasks: configure-sytem.yml

     - block:

       - name : Install Docker
         include_role:
           name: angstwad.docker_ubuntu
         vars:
           docker_group_members:
           - "{{ ansible_user_id }}"

       become: yes

     - name: Set up docker-compose
       include_tasks: configure-containers.yml

     # - name: Spin up "docker composed" apps
     #   docker_service:
     #     project_src: "{{ global_install_path }}/docker-services"
     #     state: present
     #   become: yes
