### ansible-galaxy install -r ./roles/roles_requirements.yml -p ./roles/externals/

- name: angstwad.docker_ubuntu
  src: git+https://github.com/angstwad/docker.ubuntu.git

- name: stefangweichinger.ansible-rclone
  src: git+https://github.com/stefangweichinger/ansible-rclone.git

- name: Benaud12.docker-pi
  src: git+https://github.com/Benaud12/docker-pi.git
  
- name: ansible-deploy-xwiki-tomcat-postgresql
  src: git+https://github.com:zwindler/ansible-deploy-xwiki-tomcat-postgresql.git
