### ansible-playbook playbooks/dsm-deploy/main.yml -i hosts --extra-vars "target=[TargetName] -k

- name: Delpoy DSM server
  hosts: "{{ target }}"

  vars:
    ### linux-system-base
    # basic_packages:
    #   - sudo
    #   - man
    #   - vim

  tasks:
  # - name: Load vault
  #   # include_vars: vault-example.yml
  #   include_vars: ~/Documents/Ansible/vaults/vault-dsm-deploy.yml
  #   no_log: true

# /var/services/homes/user_name/
# synouserhome --prepare-folder [user_name]

  # - name: Setup Wognet access
  #   include_role:
  #     name: linux-wognet-access

  ### SSH rights
  # chmod 644 -R ~/.ssh
  # chmod 600 -R ~/.ssh/id_rsa
  ### Fix SSH synology pubkey
  # chmod 755 ~/


  - name: Deploy Plexdrive
    include_role:
      name: linux-plexdrive
    vars:
      ansible_become: yes
      # PLEXDRIVE_CONF_SOURCE: ~/Documents/Plexdrive/plexdrive-conf.tar.gz
      # PLEXDRIVE_INSTALL_PATH: /root/plexdrive
      # PLEXDRIVE_BIN_PATH: "{{PLEXDRIVE_INSTALL_PATH}}/bin"
      PLEXDRIVE_MOUNT_POINT: /volume1/Plexdrive


### Deploy Docker using synopkg ?
