#####
# Tasks to deploy_required_packages
#####

- name: Include variables for CentOS
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'CentOS'

- name: Include variables for Ubuntu
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Ubuntu'
  
- name: Include variables for Debian
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Debian'

- name: Install basic packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ BASIC_PACKAGES }}"
  become: yes

### Block for Debian/Ubuntu 

- name: Add Docker apt repo key
  apt_key:
    keyserver: "{{ DOCKER_DEB_KEY_SERVER }}"
    id: "{{ DOCKER_DEB_KEY_ID }}"
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'  
  become: yes

- name: Add Docker apt repository
  apt_repository:
    repo: "{{ DOCKER_DEB_REPO }}"
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'  
  become: yes



###

### Block for CentOS
# RPM install missing
 
- name: Add Docker yum repository 
  yum_repository:
    name: DockerCE_Repo
    description: Official Docker repository
    baseurl:  "{{ DOCKER_RPM_REPO }}"
#    gpgkey:  "{{ DOCKER_RPM_REPO_KEY }}"
    gpgcheck: yes
  when: ansible_distribution == 'CentOS'
  become: yes
  
###