##
# ansible-playbook deluge-deploy-Ubuntu-16.04.yml --extra-vars "target=host" --ask-vault-pass --ask-sudo-pass
##

- hosts: "{{ target }}"

  remote_user: vinz
  become: yes

  vars:
    WOGNET_DELUGE_FILE_DIR: vars
    WOGNET_DELUGE_CONF: core.conf
    WOGNET_DELUGE_WEB_CONF: web.conf
    WOGNET_DELUGE_PLUGIN_WEBUI: web_plugin.conf
    WOGNET_DELUGE_PLUGIN_YARSS2: YaRSS2-1.4.3-py2.7.egg
    WOGNET_DELUGE_PLUGIN_YARSS2_CONF: yarss2.conf
    WOGNET_DELUGE_LOGROTATE_CONF: logrotate-deluge
    WOGNET_DELUGE_DEAMON_SYSTEMD_SCRIPT: deluged.service
    WOGNET_DELUGE_WEBUI_SYSTEMD_SCRIPT: deluge-web.service

## TO DO ##
# Open TCP:8112 and TCP:58846 on firewall

  tasks:
  - name: Load vault
    include_vars: vars/vault-deluge.yml
    no_log: true

  - name: Add deluge user
    user: name=deluge home=/var/lib/deluge system=yes shell=/bin/false

  - name: Add Deluge repo
    apt_repository: repo='ppa:deluge-team/ppa' update_cache=yes

  - name : Install required packages
    apt: name={{ item }} state=latest
    with_items:
        - vim
        - python
        - deluged
        - deluge-console
        - deluge-webui

  - name: Create Deluge logs dir
    file: path=/var/log/deluged state=directory recurse=yes
          owner=deluge group=deluge mode=776

  - name: Copy Deluge logrotate conf
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_LOGROTATE_CONF }}
        dest=/etc/logrotate.d/deluge
        owner=0 group=0 mode=777

  - name: Copy Deluge daemon SystemD script
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_DEAMON_SYSTEMD_SCRIPT }}
        dest=/etc/systemd/system/deluged.service
        owner=0 group=0 mode=644

  - name: Copy Deluge WebUI SystemD script
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_WEBUI_SYSTEMD_SCRIPT }}
        dest=/etc/systemd/system/deluge-web.service
        owner=0 group=0 mode=644

  - name: Reload SystemD
    command: systemctl daemon-reload

  - name: Enable Deluge Daemon SystemD auto-start
    command: systemctl enable deluged

  - name: Enable Deluge WebUi SystemD auto-start
    command: systemctl enable deluge-web
  
  - name: Start Deluge Daemon with SystemD
    systemd: name=deluged state=started

  - name: Start Deluge WebUi with SystemD
    systemd: name=deluge-web state=started

  - name: Reboot "{{ inventory_hostname }}"
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
  
  - name: Waiting for server to come back
    local_action: wait_for host={{ ansible_host }} port=22 delay=60 timeout=300
    become: no

  - name: Stop Deluge Daemon with SystemD
    systemd: name=deluged state=stopped

  - name: Stop Deluge WebUi with SystemD
    systemd: name=deluge-web state=stopped

  - name: Set user
    lineinfile: dest=/var/lib/deluge/.config/deluge/auth
                line="{{ WOGNET_DELUGE_USER }}:{{ WOGNET_DELUGE_PASSWORD }}:10"
                mode=600

  - name: Create Deluge SSL dir
    file: path=/var/lib/deluge/.config/deluge/ssl state=directory recurse=yes
          owner=deluge group=deluge mode=777

  - name: Copy SSL Key
    copy: dest="{{ item.key }}"
          content="{{ item.value.content }}"
          owner="{{ item.value.owner }}"
          group="{{ item.value.group }}"
          mode="{{ item.value.mode }}"
    with_dict: "{{ WOGNET_DELUGE_SSL_PRIVKEY }}"
    no_log: true

  - name: Copy SSL Cert
    copy: src="{{ WOGNET_DELUGE_FILE_DIR }}/daemon.cert.pem" dest=/var/lib/deluge/.config/deluge/ssl/deluge-daemon.cert.pem
          owner=deluge group=deluge mode=600

  - name: Copy Deluge plugin "YaRSS2"
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_PLUGIN_YARSS2 }}
        dest=/var/lib/deluge/.config/deluge/plugins/
        owner=deluge group=deluge mode=666

  - name: Copy Deluge "yarss2.conf"
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_PLUGIN_YARSS2_CONF }}
        dest=/var/lib/deluge/.config/deluge/yarss2.conf
        owner=deluge group=deluge mode=666

  - name: Configure "web.conf" - Enable HTTPS
    lineinfile: dest=/var/lib/deluge/.config/deluge/web.conf
                regexp="https" line="  "https"{{':'}} true,"
                state="present"

  - name: Configure "web.conf" -  pkey path
    lineinfile: dest=/var/lib/deluge/.config/deluge/web.conf
                regexp="pkey" line="  "pkey"{{':'}} "ssl/deluge-daemon.pkey.pem","
                state="present"

  - name: Configure "web.conf" - cert path
    lineinfile: dest=/var/lib/deluge/.config/deluge/web.conf
                regexp="cert" line="  "cert"{{':'}} "ssl/deluge-daemon.cert.pem","
                state="present"

  - name: Copy Deluge "core.conf"
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_CONF }}
        dest=/var/lib/deluge/.config/deluge/core.conf
        owner=deluge group=deluge mode=666

  - name: Start Deluge Daemon with SystemD
    systemd: name=deluged state=restarted

  - name: Start Deluge WebUi with SystemD
    systemd: name=deluge-web state=started

  - name: Set firewall rules for deluge clients
    ufw: rule=allow proto=tcp port={{ item }}
    with_items:
        - 8112
        - 58846
        - 7881:7891

  - name: Deluge successfully deployed !
    debug: msg="\n\tConnect to https://{{ ansible_host }}:8112 then
                \n\t- Change "deluge" default password
                \n\t
                \n\t Enjoy !"
