##
# ansible-playbook base-local-Ubuntu_16.04.yml --extra-vars "target=host" --ask-pass --ask-sudo-pass --ask-vault-pass
##

- hosts: '{{ target }}'
  remote_user: vinz
  become: yes

  vars:
    WOGNET_AUTHORIZEDKEYS: ../../pubkeys/wognet-pubkeys.txt

  tasks:
  - name: Load vault
    include_vars: vars/vault-base.yml
    no_log: true

  - name: Install basic packages
    apt: name={{ item }} state=latest
    with_items:
        - man
        - vim

  - name: Add user
    user: name={{ GENERIC_DEPLOY_USERNAME }} password={{ GENERIC_DEPLOY_PASSWORD }} shell=/bin/bash

  - name: Add deploy user to sudoers
    action: 'lineinfile
          dest=/etc/sudoers
          state=present
          regexp="^{{ GENERIC_DEPLOY_USERNAME }} ALL"
          line="{{ GENERIC_DEPLOY_USERNAME }} ALL=(ALL:ALL) ALL"'

  - name : Create ssh directory
    action: file path=/home/{{ GENERIC_DEPLOY_USERNAME }}/.ssh
          state=directory
          owner=0 group=0 mode=0755

  - name: Copy wognet authorized keys
    action: copy src={{ WOGNET_AUTHORIZEDKEYS }}
            dest=/home/{{ GENERIC_DEPLOY_USERNAME }}/.ssh/authorized_keys
            owner=0 group=0 mode=644

  - name: Add curent user pubkey to authorized_keys file
    authorized_key: user={{ GENERIC_DEPLOY_USERNAME }} key={{ item }}
    with_file:
        - ~/.ssh/id_rsa.pub

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
              regexp="PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
    notify: Restart ssh

  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="PermitRootLogin"
                line="PermitRootLogin no"
                state=present
    notify: Restart ssh

########## TODO
# Change ufw for iptables
##########  
#  - name: Set ufw policy - Allow ssh
#    ufw: proto=tcp port=22 rule=allow

#  - name: Set ufw policy - Deny all incoming
#    ufw: state=enabled direction=incoming policy=deny

  handlers:
  - name: Restart ssh
    service: name=sshd state=restarted
