- hosts: '{{ target }}'

  remote_user: tolmanbriger 
  become: yes

  vars:
    WOGNET_DELUGE_FILE_DIR: vars
    WOGNET_DELUGE_CONF: core.conf
    WOGNET_DELUGE_WEB_CONF: web.conf
    WOGNET_DELUGE_PLUGIN_WEBUI: web_plugin.conf
    WOGNET_DELUGE_PLUGIN_YARSS2: YaRSS2-1.4.3-py2.7.egg
    WOGNET_DELUGE_PLUGIN_YARSS2_CONF: yarss2.conf
    WOGNET_DELUGE_LOGROTATE_CONF: logrotate-deluge
    WOGNET_DELUGE_DEAMON_INIT_SCRIPT: deluged.conf
    WOGNET_DELUGE_WEBUI_INIT_SCRIPT: deluge-web.conf

## TO DO ##
# Open TCP:8112 and TCP:58846 on firewall

  tasks:
  - name: Load vault
    include_vars: vars/vault-deluge.yml
    no_log: true

  - name: Add deluge user
    user: name=deluge home=/var/lib/deluge system=yes shell=/bin/false

  - name: Add Deluge repo
    apt_repository: repo='ppa:deluge-team/ppa' update_cache=yes

  - name : Install required packages
    apt: name={{ item }} state=latest
    with_items:
        - vim
        - python
        - deluged
        - deluge-webui

  - name: Check Deluge conf dir
    file: path=/var/lib/deluge/.config/deluge state=directory recurse=yes
          owner=deluge group=deluge mode=776   

  - name: Copy Deluge "core.conf"
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_CONF }}
        dest=/var/lib/deluge/.config/deluge/core.conf
        owner=deluge group=deluge mode=666

    
#
#  - name: Copy Deluge Web "web.conf"
#    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_WEB_CONF }}
#        dest=/var/lib/deluge/.config/deluge/web.conf
#        owner=deluge group=deluge mode=666
#
#  - name: Copy Deluge plugin "WebUI.conf"
#    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_PLUGIN_WEBUI }}
#        dest=/var/lib/deluge/.config/deluge/web_plugin.conf
#        owner=deluge group=deluge mode=666
#
  - name: Copy Deluge plugin "YaRSS2" 
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_PLUGIN_YARSS2 }}
        dest=/var/lib/deluge/.config/deluge/plugins/
        owner=deluge group=deluge mode=666

  - name: Copy Deluge "yarss2.conf"
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_PLUGIN_YARSS2_CONF }}
        dest=/var/lib/deluge/.config/deluge/yarss2.conf
        owner=deluge group=deluge mode=666

  - name: Create Deluge logs dir
    file: path=/var/log/deluge state=directory recurse=yes
          owner=deluge group=deluge mode=776

  - name: Copy Deluge logrotate conf
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_LOGROTATE_CONF }}
        dest=/etc/logrotate.d/deluge
        owner=0 group=0 mode=777

#  - name: Create Deluge SSL dir
#    file: path=/var/lib/deluge/.config/deluge/ssl state=directory recurse=yes
#          owner=deluge group=deluge mode=777
#
#  - name: Copy SSL Key
#    copy: dest="{{ item.key }}"
#          content="{{ item.value.content }}"
#          owner="{{ item.value.owner }}"
#          group="{{ item.value.group }}"
#          mode="{{ item.value.mode }}"
#    with_dict: "{{ WOGNET_DELUGE_SSL_PRIVKEY }}"
#    no_log: true
#
#  - name: Copy SSL Cert
#    copy: src="{{ WOGNET_DELUGE_FILE_DIR }}/daemon.cert.pem" dest=/var/lib/deluge/.config/deluge/ssl/deluge-daemon.cert.pem
#          owner=deluge group=deluge mode=600
#
  - name: Copy Deluge Daemon init script
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_DEAMON_INIT_SCRIPT }}
        dest=/etc/init/deluged.conf
        owner=0 group=0 mode=644

  - name: Copy Deluge WebUI init script
    action: copy src={{ WOGNET_DELUGE_FILE_DIR }}/{{ WOGNET_DELUGE_WEBUI_INIT_SCRIPT }}
        dest=/etc/init/deluge-web.conf
        owner=0 group=0 mode=644

  - name: Start Deluge Deamon & WebUI
    service: name=deluged state=started

  - name: Enable deluge services auto-start
    service: name={{ item }} enabled=yes
    with_items:
        - deluged
        - deluge-web

  - name: Set user
    lineinfile: dest=/var/lib/deluge/.config/deluge/auth
                line="{{ WOGNET_DELUGE_USER }}:{{ WOGNET_DELUGE_PASSWORD }}:10"
                mode=600

#  - name: Login to Deluge WebUi
#    uri:
#      url: http://{{ ansible_host }}:8112
#      method: POST
#      body: "login=deluge&password=deluge&enter=Sign%20in"
#      HEADER_Content-Type: "application/json"
#      register: json_response
#
#  - name: Configure Deluge "web.conf"
#    lineinfile: dest=/var/lib/deluge/.config/deluge/web.conf
#                regexp="https" line="  "https"{{':'}} true,"
#                state=present
 
  - name: Restart Deluge deamon
    service: name=deluged state=restarted

#  - name: Start Deluge Web
#    service: name=deluge-web state=restarted
