#####
# Tasks to configure_user_access
#####

- name: Add group
  group:
    name: "{{ GENERIC_DEPLOY_USERNAME }}"
    state: present
    gid: 1010

- name: Add user
  user:
    name: "{{ GENERIC_DEPLOY_USERNAME }}"
    password: "{{ GENERIC_DEPLOY_PASSWORD }}"
    shell: /bin/bash
    uid: 1010
    group: vinz

- name: Install sudo
  package:
    name: sudo
    state: latest

- name: Configure deploy user in sudoers file
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ GENERIC_DEPLOY_USERNAME }} ALL"
    line: "{{ GENERIC_DEPLOY_USERNAME }} ALL=(ALL) ALL"

- name : Create SSH directory
  file:
    path: /home/{{ GENERIC_DEPLOY_USERNAME }}/.ssh
    state: directory
    owner: "{{ GENERIC_DEPLOY_USERNAME }}"
    group: "{{ GENERIC_DEPLOY_USERNAME }}"
    mode: 0755
  become: yes

- name: Copy SSH authorized keys
  copy:
    src: ssh-pubkeys.txt
    dest: /home/{{ GENERIC_DEPLOY_USERNAME }}/.ssh/authorized_keys
    owner: "{{ GENERIC_DEPLOY_USERNAME }}"
    group: "{{ GENERIC_DEPLOY_USERNAME }}"
    mode: 0644

- name: Add curent user pubkey to authorized_keys file (if not already exists)
  authorized_key:
    user: "{{ GENERIC_DEPLOY_USERNAME }}"
    key: "{{ item }}"
  with_file:
    - ~/.ssh/id_rsa.pub
