---
    - name: Create directory for docker-compose
      file:
        path: "{{ global_install_path }}/proxy-docker-services"
        state: directory

    - name: Copy Docker Compose file
      template:
        src: tpl_docker-compose.yml
        dest: "{{ global_install_path }}/proxy-docker-services/docker-compose.yml"

    - name: Copy sniproxy configuration file
      template:
        src: tpl_sniproxy.conf
        dest: "{{ sniproxy_config_path }}/sniproxy.conf"

    - name: Copy dnsmask configuration file
      template:
        src: tpl_dnsmasq.conf
        dest: "{{ dnsmask_config_path }}/dnsmasq.conf"
