### ansible-playbook playbooks/deploy-proxy/main.yml -i ~/Documents/Ansible/hosts --vault-password-file ~/Documents/Ansible/vault.txt -K

---
  - name: Deploy a smart proxy / jump station
    hosts: proxy

    vars:
      locale: en_US.UTF-8
      timezone: Europe/Paris
      user_uid: 1010
      user_gid: 1010
      global_install_path: "/home/{{ ansible_ssh_user }}"
      global_config_path: "/home/{{ ansible_ssh_user }}/.config"
      dnsmask_config_path: "{{ global_config_path }}/dnsmask"
      caddy_config_path: "{{ global_config_path }}/caddy"
      sniproxy_config_path: "{{ global_config_path }}/sniproxy"


    tasks:
     # - name: Load vault
     #   include_vars: vault-seedbox.yml
     #   no_log: true
      - name: Define external IP adress
        shell: wget -qO- http://ipecho.net/plain ; echo
        register: external_ip

      - name: Prepare system
        include_tasks: configure-sytem.yml

      - name : Install Docker
        include_role:
          name: angstwad.docker_ubuntu
        vars:
          docker_group_members: "{{ ansible_ssh_user }}"
        become: yes

      - name: Set up docker-compose
        include_tasks: configure-containers.yml

      - name: Spin up "docker composed" apps
        docker_service:
          project_src: "{{ global_install_path }}/proxy-docker-services"
          state: present
        become: yes
