---
version: "2"

services:
  dnsmasq-service:
    image: andyshinn/dnsmasq:latest
    container_name: dnsmasq
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - {{ dnsmask_config_path }}/dnsmasq.conf:/etc/dnsmasq.conf:ro
    restart: always

  dnsmasq-bogus-service:
    image: andyshinn/dnsmasq:latest
    container_name: dnsmasq-bogus
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    ports:
      - "5353:5353"
      - "5353:5353/udp"
    command: --port=5353 --log-facility=- -A {{ external_ip }}
    restart: always

  caddy-service:
    image: abiosoft/caddy:latest
    container_name: caddy
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - {{ caddy_config_path }}/Caddyfile:/etc/Caddyfile
      - {{ caddy_config_path }}/wwwroot:/srv
    restart: always

  sniproxy-service:
    image: ab77/sniproxy:latest
    container_name: sniproxy
    build:
      context: docker-sniproxy
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - {{ sniproxy_config_path }}/sniproxy.conf:/etc/sniproxy.conf
    restart: always
