### ansible-playbook ~/Documents/GitHub/ansible/playbooks/python-install/main.yml -i ~/Documents/Ansible/hosts --extra-vars "target=prometheus" --vault-password-file ~/Documents/Ansible/vault.txt -u "ansible_user"
---
  - name: Install Python
    hosts: '{{ target }}'
    gather_facts: False

    tasks:
     - name: install python 2
       raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
       become: yes
