#####
# Main task file for Linux to install plexdrive
#####

- name: Include generic variables
  include_vars: vars.yml

- name: Install plexdrive
  include_tasks: install-plexdrive.yml

- name: configure plexdrive
  include_tasks: setup-plexdrive.yml

- name: Enable and start PlexDrive service
  systemd:
    daemon_reload: yes
    name: "plexdrive.service"
    enabled: yes
    state: started
  become: yes
