#####
# Main task file for Linux to install plexdrive
#####
- name: Include generic variables
  include_vars: vars.yml

- name: Install prerequesites
  package:
    name:
      - fuse
    state: latest
  become: yes

- name: Download PlexDrive
  get_url:
    url: "{{ PLEXDRIVE_DL_URL }}"
    dest: "{{ PLEXDRIVE_BIN_PATH }}/plexdrive"
    mode: 0755

- name: Create PlexDrive mount directory
  file:
    path: "{{ PLEXDRIVE_MOUNT_POINT }}"
    state: directory
    mode: 0755
  become: yes

- name: Create Plexdrive configuration directory
  file:
    path: "{{ PLEXDRIVE_CONF_PATH }}"
    state: directory

- name: Extract plexdrive configuration
  unarchive:
    src: "{{ PLEXDRIVE_CONF_SOURCE }}"
    dest: "{{ PLEXDRIVE_CONF_PATH }}"

- name: Configure auto launch on Debian
  include_tasks: auto_start-debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Configure auto launch on Synology DSM
  include_tasks: auto_start-syno.yml
  when: ansible_proc_cmdline.syno_hw_version is defined
