---
- name: Simple PUT operation
  aws_s3:
    aws_access_key: "{ VAULT_AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ VAULT_AWS_SECRET_ACCESS_KEY }}"
    region: "{{ AWS_REGION }}"
    bucket: "{{ S3_BUCKET }}"
    src: /ndh/landing/ctlm/"{{ CTLM_SOURCE_NAME }}"/"{{ CTLM_ENTITY_FILENAME }}"
    object: /AFS/"{{ CTLM_SOURCE_NAME }}"/DATA/"{{ CTLM_DATE_YEAR }}"/"{{ CTLM_DATE_MONTH }}"/"{{ CTLM_DATE_DAY }}"/"{{ CTLM_ENTITY_NAME }}"/"{{ CTLM_ENTITY_TYPE }}"/"{{ CTLM_ENTITY_FILENAME }}"
    mode: put

# CTLM_SOURCE_NAME: austin
# CTLM_DATE_YEAR: 2018
# CTLM_DATE_MONTH: 11
# CTLM_DATE_DAY: 27
# CTLM_ENTITY_NAME: loans
# CTLM_ENTITY_TYPE: delta
# CTLM_ENTITY_FILENAME: any-file.name
