---
- name: Check (or create} sources directories
  delegate_to: "{{ item.public_dns_name }}"
  file:
    path: "{{ LANDING_SOURCE_DIR}}{{ item }}"
    state: directory
  with_items: "{{ LANDING_SOURCE_LIST }}"
