#####
# Tasks to deploy_required_packages
#####

- name: Include variables for CentOS
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'CentOS'

- block:
    - name: '====| ERROR : Distribution not handled by this role yet, bye |===='
      debug:
        msg: "nothing to upgrade, ending play"

    - meta: end_play
  when: ansible_distribution != 'CentOS'

#- name: Include variables for Ubuntu
#  include_vars: "{{ ansible_distribution }}.yml"
#  when: ansible_distribution == 'Ubuntu' or 
#  
#- name: Include variables for Debian
#  include_vars: "{{ ansible_distribution }}.yml"
#  when: ansible_distribution == 'Debian'

### Block for CentOS 
- name: Add EPEL repository
  yum:
    name: "{{ EPEL_YUM_REPO }}"
    state: present
  when: ansible_distribution == 'CentOS' 

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ EPEL_YUM_KEY }}"
    state: present

- name: Install basic packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ BASIC_PACKAGES }}"