#####
# Main task file for shinken_server role
#####

### CentOS only for now
- block:
    - name: Distribution compatibility check
      debug:
        msg: '====| ERROR : Distribution not handled by this role yet |===='

    - meta: end_play
  when: ansible_distribution != 'CentOS'

- name: Include common variables
  include_vars: vars-common.yml
  
- debug:
   msg: '====| PLAY : deploy_required_packages |===='
- include: deploy_required_packages.yml
  become: yes

- debug:
   msg: '====| PLAY : deploy_shinken |===='
- include: deploy_shinken.yml
  become: yes