### ansible-playbook playbooks/bitwarden-deploy/main.yml -i ~/Documents/Ansible/hosts --vault-password-file ~/Documents/Ansible/vault.txt --extra-vars "target=[TargetName]" -K -k

- name: Deploy Bitwarden in docker
  hosts: "{{ target }}"
  vars:
    vault_path: ~/Documents/Ansible/vaults/vault-bitwarden-deploy.yml
    install_path: "/home/{{ username }}/"

  tasks:
  tasks:
    - name: Load vault
      include_vars: "{{ vault_path }}"
      no_log: true

    - name: Deploy docker
      include_role:
        name: angstwad.docker_ubuntu
        apply:
          become: yes
      vars:
        docker_group_members:
        - "{{ username }}"

    - name: Download Bitwarden install script
      get_url:
        url: https://go.btwrdn.co/bw-sh
        dest: "{{ install_path }}/bitwarden.sh"
        mode: '0550'
