#####
# Main task file for plex_server role
#####

### Debian/Ubuntu only for now
- block:
    - name: '====| ERROR : Distribution not handled by this role yet |===='
      debug:
        msg: '====| Bye ! |===='

    - meta: end_play
  when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'Debian' 

- name: Include common variables
  include_vars: vars-common.yml

- debug:
    msg: '====| PLAY : deploy_packages |===='
- import_tasks: deploy_packages.yml

- debug:
    msg: '====| PLAY : configure_plex |===='
- import_tasks: configure_plex.yml