## Vault variables
# GCP_SERVICE_ACCOUNT_EMAIL:
# GCP_AUTH_FILE:
# GCP_PROJECT:

INVENTORY_DIR: /ansible/inventories/

## Environnement settings for default
GCP_REGION: australia-southeast1
GCP_ZONE: australia-southeast1-b
GCP_AUTH_KIND: serviceaccount

# Vars for gcp-create-instance.yml tasks
GCP_INSTANCE_USER: vinz
GCP_INSTANCE_NAME: vision
GCP_INSTANCE_TYPE: n1-standard-2
GCP_IMAGE_URI: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20210623
GCP_INSTANCE_PYTHON_PATH: /usr/bin/python3
GCP_DISK_NAME: "ssd-{{ GCP_INSTANCE_NAME }}"
GCP_INSTANCE_DISK_SIZE_GB: 50

# Vars for linux-plexdrive role
PLEXDRIVE_MOUNT_POINT: /mnt/PlexDrive
PLEXDRIVE_CONF_SOURCE: /ansible/plexdrive-conf.tar.gz
PLEXDRIVE_BIN_PATH: /usr/local
PLEXDRIVE_CONF_PATH: /root/.plexdrive

# Vars for deploy-plex.yml tasks
### Get a PlexClaim here : https://plex.tv/claim
PLEX_CLAIM: claim-oAAi1-9XT4my5W3--p9f
PLEX_DOCKER_PATH: "/home/{{ GCP_INSTANCE_USER }}/docker/plex"
PLEX_CONF_ARCHIVE: "/home/{{ GCP_INSTANCE_USER }}/alfred_plex_library.tar.gz"
