---
## Variables from vault
# grafana_security:
  # admin_user: "admin"
  # admin_password: "pass"

grafana_auth:
  anonymous:
    enabled: true

grafana_datasources:
- name: "Prometheus"
  type: "prometheus"
  access: "proxy"
  url: "http://127.0.0.1:9090"
  isDefault: true

grafana_dashboards: []
