### ansible-playbook playbooks/proxmox-setup/main.yml -i hosts --extra-vars "target=[TargetName]" -K

- name: Proxmox Hypervisor setup
  hosts: "{{ target }}"
  vars:
    os_auth_pw_max_age: 99999
    os_auth_timeout: 120
    os_auth_pam_passwdqc_enable: false
    #ufw_manage_defaults: false
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding (required for VMs routing)
      net.ipv4.ip_forward: 1
  tasks:
    - name: Apply generic system configuration
      include_role:
        name: linux-system-base
    - name: Apply OS hardening role
      include_role:
        name: dev-sec.os-hardening
        apply:
          become: yes
    - name: Setup Wognet access
      include_role:
        name: linux-wognet-access
    - name: Disable ssh root access
      include_role:
        name: linux-disable-root-access
