### ansible-playbook playbooks/prometheus-deploy/main.yml -i hosts --extra-vars "target=[TargetName] -k

- name: Delpoy monitoring server
  hosts: "{{ target }}"

  vars:
    ### linux-system-base
    # basic_packages:
    #   - sudo
    #   - man
    #   - vim

  tasks:
  # - name: Load vault
  #   # include_vars: vault-example.yml
  #   include_vars: ~/Documents/Ansible/vaults/vault-prometheus-deploy.yml
  #   no_log: true

  - name: Deploy Prometheus
    include_role:
      name:
      - cloudalchemy.prometheus
      - cloudalchemy.alertmanager

  - name: Deploy grafana
    hosts: grafana
    roles:
    - cloudalchemy.grafana
