### ansible-playbook playbooks/prometheus-deploy/main.yml -i ~/Documents/Ansible/hosts --vault-password-file ~/Documents/Ansible/vault.txt --extra-vars "target=<target>" -K

- name: Delpoy monitoring server
  hosts: "{{ target }}"

  tasks:
  - name: Load vault
    include_vars: ~/Documents/Ansible/vaults/vault-prometheus-deploy.yml
    no_log: true

  - name: Include all files in vars
    include_vars:
      dir: vars/

  # - name: Deploy Prometheus
  #   include_role:
  #     name: cloudalchemy.prometheus
  #
  # - name: Deploy Alert Manager
  #   include_role:
  #     name: cloudalchemy.alertmanager

  - name: Deploy grafana
    include_role:
      name: cloudalchemy.grafana

  # - name: Configuration for Synology
  #   include_tasks: tasks/configure_syno.yml
