### ansible-playbook playbooks/pve-deploy/main.yml -i hosts --extra-vars "target=[TargetName] -u root

- name: Delpoy PVE hypervisor
  hosts: "{{ target }}"

  vars:
    ### linux-system-base
    # basic_packages:
    #   - sudo
    #   - man
    #   - vim
    ### dev-sec.os-hardening
    os_auth_pw_max_age: 99999
    os_auth_timeout: 120
    os_auth_pam_passwdqc_enable: false
    #ufw_manage_defaults: false
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding (required for VMs routing)
      net.ipv4.ip_forward: 1
    ### configure-system
    LOCALE: en_US.UTF-8
    # TIMEZONE: Europe/Paris
    DEPLOY_PATH: "/home/{{USERNAME}}"
    ### configure-network
    PUBLIC_IFACE: enp2s0
    VM_IFACE: vmbr0
    VM_INT_NET: 192.168.9.0/24
    ### deploy-dsm
    DSM_VM_ID: 101
    DSM_STORAGE_VOL: local
    DSM_VM_BACKUP_PATH: "{{DEPLOY_PATH}}/vzdump-qemu-102-2020_01_01-10_36_13.vma.gz"
    DSM_VCPU_COUNT: 4
    DSM_STORAGE_PV: /dev/sdb1
    DSM_STORAGE_VG: vg_dsm_data
    DSM_STORAGE_NAME: dsm-data
    DSM_DISK_SIZE_GB: 1000

  tasks:
  - name: Load vault
    # include_vars: vault-example.yml
    include_vars: ~/Documents/Ansible/vaults/vault-pve-deploy.yml
    no_log: true

  # - name: Setup Wognet access
  #   include_role:
  #     name: linux-wognet-access
  #
  # - name: Apply generic system configuration
  #   include_role:
  #     name: linux-system-base

  # - name: Configure fail2ban
  #   include_tasks: tasks/configure-fail2ban.yml

  # - name: Apply OS hardening role
  #   include_role:
  #     name: dev-sec.os-hardening
  #
  # - name: Configure system
  #   include_tasks: tasks/configure-system.yml
  #
  # - name: Configure network
  #   include_tasks: tasks/configure-network.yml
  #
  # - name: Configure Proxmox VE
  #   include_tasks: tasks/configure-pve.yml

  # # SOURCE: https://github.com/zwindler/ansible-proxmoxve
  # - name: Configure PVE user
  #   include_tasks: tasks/configure-pve-user.yml

  # - name: Configure proxmoxer api access
  #   include_tasks: tasks/configure-promoxer.yml

  - name: Deploy DSM VM
    include_tasks: tasks/deploy-dsm.yml

  # - name: Reboot Sam
  #   shell: sleep 2 && shutdown -r now "Ansible post-install reboot"
  #   async: 1
  #   poll: 0
  #
  # - name: Waits for ping
  #   wait_for:
  #     host: "{{ansible_default_ipv4.address}}"
