#####
# Tasks to configure Ansible access for Linux
#####

- name: Create ansible group
  group:
    name: ansible
    state: present
  become: yes

- name: Create ansible user
  user:
    name: ansible
    group: ansible
  become: yes

- name: Add ansible sudoers file
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^ansible ALL"
    line: "ansible ALL=(ALL) ALL"
  become: yes

- name: Set ansible authorized public key
  authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', 'vars/ansible_rsa.pub') }}"
  become: yes
