#####
# Tasks to deploy_required_packages
#####

- name: Include variables for CentOS
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'CentOS'

- name: Include variables for Ubuntu
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Ubuntu'
  
- name: Include variables for Debian
  include_vars: "{{ ansible_distribution }}.yml"


- name: Install basic packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ BASIC_PACKAGES }}"
  become: yes
  
- name: Install acdcli using pip
  pip:
    name: "git+https://github.com/yadayada/acd_cli.git"
    editable: false
    extra_args: '--upgrade'
    virtualenv_command: pyvenv  
    virtualenv: "{{ ACD_INSTALL_PATH }}" 
  become: yes
  when: ansible_distribution == 'Debian'

- name: Install acdcli using pip
  pip:
    name: "git+https://github.com/yadayada/acd_cli.git"
    editable: false
    extra_args: '--upgrade'
    virtualenv_command: pyvenv  
    executable: pip3
  become: yes
  when: ansible_distribution == 'Ubuntu'
  

