### ansible-playbook playbooks/AWS/EC2-create.yml -i ~/Documents/host.ini --vault-password-file ~/Documents/vault.txt
---
  - name: Provision an EC2 Instance
    hosts: local
    connection: local
    gather_facts: False
#    tags: provisioning
    # Necessary Variables for creating/provisioning the EC2 Instance
    vars:
      instance_type: t2.micro
      security_group: ansible-ssh
      image: ami-e2021d81
      keypair: xmac
      region: ap-southeast-2
      count: 1
      host_file: "./hosts-aws_auto.ini"
      instance_user: ubuntu

    # Task that will be used to Launch/Create an EC2 Instance
    tasks:
      - name: Load vault
        include_vars: vault-aws.yml
        no_log: true    
    
      - name: Export local variables
        shell:
          export AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }} 
          export AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}

      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group for webserver Servers
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall
        
      - name: Launch the new EC2 Instance
        local_action: ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2_result

      - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
        local_action: lineinfile 
                      dest="{{ host_file }}" 
                      regexp={{ item.public_dns_name }}
                      insertafter="[aws]"
                      line="\n{{ item.public_dns_name }} ansible_host={{ item.public_ip }} ansible_user={{ instance_user }}"
        with_items:  "{{ ec2_result.instances }}"

      - name: Wait for SSH to come up
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: "{{ ec2_result.instances }}"

      - name: Adding ec2 instance as host for running python install
        add_host:
          name: "{{ item.public_dns_name }}"
          ansible_host: "{{ item.public_dns_name }}"
          ansible_user: ubuntu
        with_items: "{{ ec2_result.instances }}"

      - name: Installing python
        delegate_to: "{{ item.public_dns_name }}"
        raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
        with_items: "{{ ec2_result.instances }}"
