---
    - name: Create directory for docker-compose
      file:
        path: "{{ global_install_path }}/docker-seedbox"
        state: directory

    - name: Copy Docker Compose file
      template:
        src: tpl_docker-compose.yml
        dest: "{{ global_install_path }}/docker-seedbox/docker-compose.yml"
