---
  - name: HTTPS APT transport for MKVToolNix repository
    apt:
      name: apt-transport-https
      state: present
    become: yes

  - name: Add MKVToolNix repository key
    apt_key:
      url: "{{ mkvtoolnix_apt_key_url }}"
      state: present
    become: yes

  - name: Add MKVToolNix repository and update apt cache
    apt_repository:
      repo: "{{ mkvtoolnix_apt_repo }}"
      mode: '644'
      update_cache: yes
      state: present
    become: yes

  - name : Install MKVToolNix package
    apt:
      name: mkvtoolnix
      state: latest
    become: yes

  - name : Create muxing directories
    file:
      path: "{{ download_path }}/Muxed"
      state: directory
      mode: 0755

  - file:
      path: "{{ download_path }}/@ToMux/{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - Vids
      - Subs

  - name: Set up and copy AddMkvSubs.sh
    template:
      src: tpl_AddMkvSubs.sh
      dest: "{{ global_install_path }}/scripts/AddMkvSubs.sh"
      mode: 0755
