##
##

- hosts: "{{ target }}"

  remote_user: vinz
  become: yes

  vars:
    WOGNET_AFP_FILE_DIR: vars
    WOGNET_AFP_NETATALK_VERSION: netatalk-3.1.9

  tasks:
  - name: Load vault
    include_vars: vars/vault-afp.yml
    no_log: true

  - name : Install required packages
    apt: name={{ item }} state=latest
    with_items:
        - build-essential
        - libevent-dev
        - libssl-dev
        - libgcrypt-dev
        - libkrb5-dev
        - libpam0g-dev
        - libwrap0-dev
        - libdb-dev
        - libtdb-dev
        - libmysqlclient-dev
        - avahi-daemon
        - libavahi-client-dev
        - libacl1-dev
        - libldap2-dev
        - libcrack2-dev
        - systemtap-sdt-dev
        - libdbus-1-dev
        - libdbus-glib-1-dev
        - libglib2.0-dev
        - libio-socket-inet6-perl
        - tracker
        - libtracker-sparql-1.0-dev
        - libtracker-miner-1.0-dev

  - name: Extract Netatalk sources directory
    unarchive: src={{ WOGNET_AFP_FILE_DIR }}/{{ WOGNET_AFP_NETATALK_VERSION }}.tar.bz2 dest=/tmp/

  - name: Configure sources for compilation
    command: chdir=/tmp/{{ WOGNET_AFP_NETATALK_VERSION }}
             ./configure \
             --with-init-style=debian-systemd \
             --without-libevent \
             --without-tdb \
             --with-cracklib \
             --enable-krbV-uam \
             --with-pam-confdir=/etc/pam.d \
             --with-dbus-daemon=/usr/bin/dbus-daemon \
             --with-dbus-sysconf-dir=/etc/dbus-1/system.d \
             --with-tracker-pkgconfig-version=1.0

  - name: Compile and install Netatalk
    make: chdir=/tmp/{{ WOGNET_AFP_NETATALK_VERSION }}
          target=install
    
  - name: Set firewall rules for afp throught vpn tunnel 
    ufw: rule=allow interface=tun0

  - name: Enable SystemD auto-start
    systemd: name={{ item }} enabled=yes state=restarted
    with_items:
        - avahi-daemon
        - netatalk
