#####
# Tasks to deploy_required_packages
#####

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items: "{{ required_packages }}"

    # Upgrade pip with pip to fix angstwad/docker.ubuntu/pull/35 and docker-py/issues/525
    - name: Install pip, setuptools, docker-py and docker-compose with pip
      pip:
        name: "{{ item.name }}"
        state: present
        executable: pip
      with_items:
        - name: pip
        - name: setuptools
        - name: docker-py
        - name: docker-compose
