### ansible-playbook playbooks/deploy-raspi_vpn/main.yml -i ~/Documents/Ansible/hosts --vault-password-file ~/Documents/Ansible/vault.txt -K

---
  - name: Deploy a vpn router
    hosts: vpn

    vars:
      locale: en_US.UTF-8
      timezone: Australia/Sydney
      user_uid: 1010
      user_gid: 1010
      global_install_path: "/home/{{ ansible_ssh_user }}"
      global_config_path: "/home/{{ ansible_ssh_user }}/.config"
      # dnsmask_config_path: "{{ global_config_path }}/dnsmask"
      # caddy_config_path: "{{ global_config_path }}/caddy"
      # sniproxy_config_path: "{{ global_config_path }}/sniproxy"
      required_packages:
        - python-dev
        - python-pip

    tasks:
     # - name: Load vault
     #   include_vars: vault-seedbox.yml
     #   no_log: true


      - name : Install Docker
        include_role:
          name: Benaud12.docker-pi
        vars:
          docker_pi_group_users: "{{ ansible_ssh_user }}"
        become: yes

      - name: Deploy required packages
        include_tasks: deploy_required_packages.yml
        become: yes

      - name: Set up docker-compose
        include_tasks: configure-containers.yml

      - name: Spin up "docker composed" apps
        docker_service:
          project_src: "{{ global_install_path }}/vpn-docker-services"
          state: present
        become: yes
