---
    - name: Create directory for docker-compose
      file:
        path: "{{ global_install_path }}/docker-gitlab"
        state: directory

    - name: Copy Docker Compose file
      template:
        src: tpl_docker-compose_gitlab.yml
        dest: "{{ global_install_path }}/docker-gitlab/docker-compose.yml"
